name: Deploy API docs

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docs
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'build-docs openapi.json --output docs/index.html'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/'
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
